name = "荒野建国 · Wilderness Nation"
author = "142093601"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46ac18e52c5f68215f3e7fa8db6b995e352312d59b4495a2a64b7ad279564ce2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
