name = "荒野建国 · Wilderness Nation"
author = "142093601"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12b2ab7cad738711e6b9c0bc32b6ec8bc5baf507e3c6664e3964ffed30682da5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
