name = "荒野建国 · Wilderness Nation"
author = "142093601"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5a68565c0fb20a55826152b9b1ecd6b6a0dfcdfeab81403156f10bde67b20e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
